### PR TITLE
Add port_from_dynamic

### PR DESCRIPTION
**Pull request by rockerBOO**
Replicates behavior similar to pid_from_dynamic for handling ports

### CODE REVIEW

**Review by lpil — COMMENTED** [review]
Thank you. Could you add some tests and update the changelog please

**Comment by rockerBOO** [comment]
Added tests and updated changelog

**Review by lpil — APPROVED** [review]
Thank you

**Comment by lpil** [comment]
Would you mind rebasing on main please 🙏

**Comment by rockerBOO** [comment]
rebased

**Comment by rockerBOO** [comment]
Maybe all the Port code should be in `gleam_erlang` because it's not really OTP related?

**Review by lpil — APPROVED** [review]
Thank you!

**Comment by lpil** [comment]
> Maybe all the Port code should be in gleam_erlang because it's not really OTP related?

Just saw this after my review. You are totally right! We should move it there

**Comment by rockerBOO** [comment]
Made a PR over there https://github.com/gleam-lang/erlang/pull/55. 

I think we should deprecate Port on here and use the one in `gleam_erlang` that I added. I think that is what confused me because I had already started work for the ports on gleam_erlang but they used the Port in OTP.

**Comment by lpil** [comment]
Good idea. Would you mind changing this to deprecate it with a message to use gleam_erlang? Thanks

**Review by lpil — APPROVED** [review]
Thank you!!

**Pull request merged**
