### PR TITLE
task.await_forever and task.try_await_forever

### PR DESCRIPTION
**Pull request by TanklesXL**
Noticed these were missing but that there is a `process.receive_forever` so I figured It might be worth including these

### CODE REVIEW

**Review by lpil — COMMENTED** [review]
Very nice! Are these TODO comments still to come?

**Comment by TanklesXL** [comment]
@lpil i kept the same TODO comments as you had for `task.try_await` and `task.await` since I thought the testing of these would be related to future plans for testing those, in terms of unit tests I was only going to add some for `await_forever`

**Comment by TanklesXL** [comment]
@lpil i've updated the tests a bit and removed those TODO comments, how does this seem?

**Review by lpil — APPROVED** [review]
Oh yes, I had totally forgotten about those TODOs from me.

Looks great, thank you!

**Pull request merged**
